### ISSUE TITLE
Error RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: Inability to pay some fees , e.g. account balance too low

### ISSUE THREAD

**Issue by makemygame** [5ire-tech/wasm-contract-deployment#10]
Hello
Use the following guide to deploy a smart contract on the 5ire Native chain using a script.
https://docs.5ire.org/docs/DeploySmartContracts/NativeChain_WASM

Error:

2023-03-11 21:56:46        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: Inability to pay some fees , e.g. account balance too low

**Comment by dung5ire** [comment]
Thanks. We will release new version soon to fix this issue

**Comment by 3lang3** [comment]
same issue.
pls fix.

**Comment by dung5ire** [comment]
Fixed it, but we need time to release the next version.
You can send me your address. I will send you token that you are able to deploy wasm smart contract

**Comment by makemygame** [comment]
> 

my address: 5DquaoYhfk4tvMZUsaP6tCYRWvmDzn8ZwzZxuFvZRQ2xg7mx
thanks

**Comment by 3lang3** [comment]
> Fixed it, but we need time to release the next version. You can send me your address. I will send you token that you are able to deploy wasm smart contract

My address: 5DvMqqaQWXR3VgYfLDg5yiN6eUjDr1GkAhmmx5hDWmdK2z7p
Wait for new release.

**Comment by 3lang3** [comment]
if need any fe help. i can pr

**Comment by secsec2025** [comment]
> Fixed it, but we need time to release the next version. You can send me your address. I will send you token that you are able to deploy wasm smart contract

I am having the same issue. Could you please send some gas fees?
5DmkijT4e3BmPQViT5uQiGAkddh8oT8FYKbo7k7X3HjPZjjr

**Comment by Elroy-pb** [comment]
> Fixed it, but we need time to release the next version. You can send me your address. I will send you token that you are able to deploy wasm smart contract
I am having the same issue too. please help me,thanks
5CRXfNXpTutmKwkGkJ4zUHKm2aLsaF5XZ4kKnUTQwtrGDCMi

**Comment by Elroy-pb** [comment]
I am having the same issue too. please help me,thanks
5CRXfNXpTutmKwkGkJ4zUHKm2aLsaF5XZ4kKnUTQwtrGDCMi

**Comment by tct68** [comment]
I am having this issue too, pls give me some fees. many thanks.
5DVUUgULjnHPeWYNdj7hkEA3VMqL6PTj4Gy8M6eEZpSqm2Hd

**Comment by dung5ire** [comment]
Done

**Comment by makemygame** [comment]
> Thanks. We will release new version soon to fix this issue
pls give me some fees. many thanks.
5DquaoYhfk4tvMZUsaP6tCYRWvmDzn8ZwzZxuFvZRQ2xg7mx

**Comment by kenhcrypto** [comment]
> Done

I am having the same issue. Could you please send some gas fees?
5CPt2at3DjFpiwUnPDH9iJPVP1563725jG8NYEa7psvivafN

**Comment by vcrlab** [comment]
I am having this issue too, pls give me some fees. many thanks.
5CERZqGhzXZLsN6bSsfT5s1PAjAT2hkCEiMsY2vL7bZrrKXf

**Comment by thanhliem74** [comment]
I am having this issue too, pls give me some fees. many thanks.
0x0a9E9988C0331ad4B072bD6aCDF40EF18f863cC6

**Comment by thanhliem74** [comment]
I am having this issue too, pls give me some fees. many thanks.
5FovKys1f1G6koFP1gmuhMvsmpqmzEEyjdNeEpcb9FpQhQM9

**Comment by vnpeace68** [comment]
I am having this issue too, pls give me some fees. many thanks.
5EQzbtmtAgJ4zNiGhkS4UNwsqojesT66YWdA8ye4fzhHsDcB

**Comment by vnpeace6868** [comment]
I am having this issue too, pls give me some fees. many thanks.
5GJ4jVX15w5pFRq8Ef8zNymdyBqKnHbPPPCxqZDC1y2xLume

**Comment by haihkht** [comment]
I am having this issue too, pls give me some fees. many thanks.
5GqBon3Q4u2Vh9jRrZDU8GRZitGnVReWbs2brt3t1ZkFPvh3

**Comment by thanhliem741** [comment]
I am having this issue too, pls give me some fees. many thanks.
5FH9jhvngasG488dHa43iq1joEkVNp5uaHUGsLhEPfDFit9u

**Comment by dung5ire** [comment]
done

**Comment by Minh962** [comment]
I am having this issue too, pls give me some fees. many thanks.
5GiC3EfP3rfUtzqV5UDRTGU79Mu4q2bZw6AJey2g5U6cLZ5h

**Comment by dung5ire** [comment]
done

**Comment by umersaeed1211** [comment]
0x54FbC97734Ba26DC2BAB787135Ec590ae99cF257

**Comment by umersaeed1211** [comment]
> 0x54FbC97734Ba26DC2BAB787135Ec590ae99cF257

Please fixe my issues this my wallet

**Comment by dung5ire** [comment]
@umersaeed1211 Incorrect address

**Comment by kevinchensr** [comment]
I am having this issue too
5EvDm7mC8MPWYMZ3DSnhzPHphHn5LozcgsEiDdLyKRWp5FLb

**Comment by umersaeed1211** [comment]
> @umersaeed1211 Incorrect address

5HmDf4CNtdQLwTAYzU7mphyHh1TYLSxJXhERcmWJKe1vEbBT

0xD1A1EF14dD860D5D78C8946F9ddBb6381d707241

**Comment by dung5ire** [comment]
done

**Comment by kursatilhan** [comment]
5Emtfsq6BWcVyb3xu1t7aDkRmcLzz8bkApguJ4QfBojdKj3d

0x5E48D5831c75E36f9B9E1423eBdE308724d3cF6d

**Comment by Dayo-Adewuyi** [comment]
i am having the same issue, my address is 5EmQq8h4tqx5XLdLbRQH2RcUmPMskkHzEPh4aNekHZCXUb9U

**Comment by hodltorich** [comment]
I am having this issue too
5CzWxtTdzgzoqbHCw1aB4BmYkeFyq2LxnWHjw8fAdxmCTe4x

**Comment by simsekerkan** [comment]
RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: Inability to pay some fees , e.g. account balance too low           :(  same issue 

my adress is 5DcEHQgFzu3GiR6Sxmm6FLEL8LUNpKoJQKwQfs33dPzNJw8x

**Comment by A7MD995** [comment]
I'm having the same issue please
5EtrDBdSxF3ncDVtypjJhPk5meM99WDC2in28CvacnFZVHzu

**Comment by Albert-Tran** [comment]
I am having the same issue
My address is 5CmGNpzjPFN3xomaTSikWjJjHhvnkCxZ2Q4Nj56TJqw6weaH

**Comment by Albert-Tran** [comment]
> I am having the same issue My address is 5CmGNpzjPFN3xomaTSikWjJjHhvnkCxZ2Q4Nj56TJqw6weaH

@dung5ire could u pls resend to 5CosHNFj3U1fihFK4wKP4RXwKSSXMPJLqb9NHYAaE9dTEdGi ?

**Comment by dung5ire** [comment]
Done

**Comment by Albert-Tran** [comment]
Hi @dung5ire , i still get this error 
![image](https://github.com/5ire-tech/wasm-contract-deployment/assets/53705980/7d108c47-c1dc-4a2f-806d-a6eefa10da85)
Do u have any solution for my error?

**Comment by dung5ire** [comment]
Hey , I think you should `git pull` our latest code again. It's still working from my side now

**Comment by Albert-Tran** [comment]
@dung5ire , thank u so much. It's working now

**Comment by Albert-Tran** [comment]
Hi @dung5ire , could u pls resend to 
5EZ9kmczzpVmN5mzQMHkNLEfFZHWtpCx4f1FTesf2LGJWnsh
and 
5EvFCLyQ1Lph4hkmbzRR7NS88pMKuJh8m29AmJv7KfQQfMvF

**Comment by dung5ire** [comment]
Done

**Comment by Albert-Tran** [comment]
Hi could u pls send 5ire on testnet
 to 5FvRQn4xiDLp7BU71Wf37jvjbyqTzn49NKXuCZNC5G2ujQiE
